server:
  port: 8183

spring:
  application:
    name: authserver
  # 数据源
  datasource:
    url: jdbc:mysql://192.168.30.128:3306/cloud-test?characterEncoding=utf-8&useSSL=false
    username: admin
    # Jasypt加密 可到common-utils中找到JasyptUtil加解密工具类生成加密结果 格式为ENC(加密结果) admin2017
    password: ENC(l0z1ubd4XprWmBrKjE/5/2iE7XjuD4fs)
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    logSlowSql: true
    # Druid StatViewServlet配置
    druid:
      stat-view-servlet:
        # 默认true 内置监控页面首页/druid/index.html
        enabled: true
        url-pattern: /druid/*
        # 允许清空统计数据
        reset-enable: true
        login-username: admin
        login-password: ENC(l0z1ubd4XprWmBrKjE/5/2iE7XjuD4fs)
        # IP白名单 多个逗号分隔
        allow:
        # IP黑名单
        deny:
  http:
    servlet:
      multipart:
        enabled: true   # 启用http上传处理
        max-file-size: 100MB # 设置单个文件的最大长度
        max-request-size: 100MB # 设置最大的请求文件的大小
        file-size-threshold: 1MB  # 当上传文件达到1MB的时候进行磁盘写入
        location: /tmp  # 上传的临时目录

  jpa:
    show-sql: true
    # 自动生成表结构
    generate-ddl: true
    hibernate:
      ddl-auto: none

  redis:
    database: 15
    password: admin123456
    timeout: 3000
    sentinel:
      master: mymaster
      nodes: 192.168.31.166:26379
    jedis:
      pool:
        max-active: 5000 #最大连接数
        max-idle: 30 #最大空闲连接数
        min-idle: 5 #最小空闲连接数
        max-wait: 3000  #获取连接最大等待时间 ms  #default -1

  # 定时任务
  quartz:
    # 任务信息存储至数据库
    job-store-type: jdbc
  # 文件大小上传配置
  servlet:
    multipart:
      max-file-size: 5Mb
      max-request-size: 5Mb

# 配置文件加密key
jasypt:
  encryptor:
    password: oss

oss:
  # 全局限流
  rateLimit:
    enable: true
    # 每1秒内
    timeout: 1000
    # 总限制100个请求
    limit: 100
  # token过期时间（分钟）
  tokenExpireTime: 60
  # 用户选择保存登录状态对应token过期时间（天）
  saveLoginTime: 7
  # 限制用户登陆错误次数（次）
  loginTimeLimit: 10
  # 错误超过次数后多少分钟后才能继续登录（分钟）
  loginAfterTime: 10
  # ES
  elasticsearch:
    nodeClient: 192.168.31.201:9200
  # 日志记录方式 true使用Elasticsearch记录 false记录至数据库中
  logRecord:
    es: false
  # mob api配置 mob官网注册申请即可
  mob:
    appKey: 你的appKey

# 忽略鉴权url
ignored:
  urls:
    - /api/**
    - /oss/permission/getMenuList/**
    - /oss/user/regist
    - /oss/common/**
    - /oss/uploader/**
    - /druid/**
    - /swagger-ui.html
    - /swagger-resources/**
    - /swagger/**
    - /actuator/**
    - /**/v2/api-docs
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico
    - /test/**

# Swagger界面内容配置
swagger:
  enabled: true
  title: 鉴权中心接口swagger
  description: 鉴权中心相关接口调用
  version: 1.0
  license: yu
  licenseUrl:
  termsOfServiceUrl:
  contact:
    name: yu
    url:
    email:
  base-package: org.yuhan.ziyu.auth
  base-path: /**
  exclude-path: /error, /ops/**

# Mybatis-plus
mybatis-plus:
  # 放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: org.yuhan.ziyu.auth.entity
  typeEnumsPackage: org.yuhan.ziyu.auth.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断",2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志
logging:
  file: oss-logs/oss.log
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: info

prop:
  upload-folder: E:\data\appdata\upload

management:
  info:
    git:
      mode: full
    build:
      enabled: true
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    db:
      enabled: true
    redis:
      enabled: true
    diskspace:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      enabled: true
      show-details: always
    info:
      enabled: true